name: Github Action - DNS Resolve
on: [push]

jobs:
  dns_resolve_test:
    runs-on: ubuntu-latest
    name: A job to test resolution
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Working DNS Resolution
        uses: ./ # Uses an action in the root directory
        id: conn
        with:
          remotehost: 'google.com'
          recordtype: 'A'